name: users
description: "kkanbufs_fe-users"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  url_launcher: ^6.0.9
  qr_flutter: ^4.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: YeojuCeramic
      fonts:
        - asset: assets/font/YeojuCeramic.otf
          weight: 800
        - asset: assets/font/YeojuCeramic.otf
          weight: 700
        - asset: assets/font/YeojuCeramic.otf
          weight: 400
        - asset: assets/font/YeojuCeramic.otf
          weight: 300

  assets:
    - assets/images/kkanbufs-logo-title.png
    - assets/images/welcome_logo.png
    - assets/images/colleges/
    - assets/images/colleges/clover.png
    - assets/images/colleges/perfect.png
    - assets/images/colleges/reburning.jpg
    - assets/images/colleges/togather.jpg
    - assets/images/colleges/unique.jpg
    - assets/images/colleges/fav_back.jpeg
    - assets/font/
    - assets/icon/
    - assets/icon/affiliates/codeit-logo.png
    - assets/icon/affiliates/codetree-logo.png
    - assets/icon/affiliates/comento-logo.jpeg
    - assets/icon/affiliates/eduwill-logo.png
    - assets/icon/affiliates/hackers-logo.jpeg
    - assets/icon/affiliates/inflearn-logo.jpeg
    - assets/icon/affiliates/siwon-logo.jpeg
    - assets/icon/affiliates/wanted-logo.jpeg
    - assets/icon/affiliates/aladin-logo.png
    - assets/icon/affiliates/jobplanet-logo.png
    - assets/icon/affiliates/megastudy-logo.jpeg
    - assets/icon/affiliates/pmg-logo.png
    - assets/lang/